[ADD] purchase_report_shipping_address
OCA/purchase-reporting pull request #49
Opened 2023-01-05 01:27 UTC by AungKoKoLin1997

This module adds warehouse address details with translatable in warehouse to show in purchase report.

In some countries where the dominant language is not based on Roman alphabet,
it is often necessary to be able to print the shipping address depends on supplier's language.
So, warehouse address details will be displayed in purchase report as a shipping address.

2023-01-05 03:38 UTC, yostashiro requested changes
Please add CONFIGURE.rst.

2023-01-05 03:38 UTC, yostashiro commented on purchase_report_shipping_address/reports/purchase_quotation_templates.xml
> +        </xpath>
```suggestion
        <xpath expr="//div[@t-if='o.dest_address_id']" position="attributes">
            <attribute name="t-att-style">'display: none!important' if o.picking_type_id.warehouse_id.warehouse_address_details else ''</attribute>
        </xpath>
        <xpath expr="//div[@t-if='o.dest_address_id']" position="after">
            <div t-else="">
                <span
                    t-field="o.picking_type_id.warehouse_id.warehouse_address_details"
                />
            </div>
        </xpath>
```
Can you try and see if this works.  Do the same for purchase order if it does.

2023-01-05 03:38 UTC, yostashiro commented on purchase_report_shipping_address/readme/DESCRIPTION.rst
> +So, warehouse address details will be displayed in purchase report as a shipping address.
```suggestion
It is necessary to be able to print the purchase documents in supplier's language,
however Odoo by defaultit does not come with the ability to present the warehouse address
in different languages.  This module intends to take care of this shortcoming.
```

2023-01-05 12:57 UTC, yostashiro commented on purchase_report_shipping_address/readme/CONFIGURE.rst
> +#. Add address in warehouse address details field.
```suggestion
#. Go to *Inventory > Configuration > Warehouses* and open a warehouse record for which the address presentation should be adjusted for purchase reports.
#. Update Warehouse Address Details field.
```

2023-01-05 12:57 UTC, yostashiro commented on purchase_report_shipping_address/readme/DESCRIPTION.rst
> +This module adds warehouse address details with translatable in warehouse to show in purchase report.
```suggestion
This module adds the translatable Warehouse Address Details field in warehouse to show in purchase reports.
```

2023-01-05 12:57 UTC, yostashiro commented on purchase_report_shipping_address/readme/DESCRIPTION.rst
> +in different languages.  This module intends to take care of this shortcoming.
```suggestion
It is necessary to be able to print the purchase documents in supplier's language,
however Odoo by defaultit does not come with the ability to present the warehouse address
in different languages.  This module intends to take care of this shortcoming.
```
```suggestion
Purchase documents are printed in supplier's language, however Odoo by default does not
come with the ability to present the warehouse address in different languages.
This module intends to take care of this shortcoming.
```

2023-01-05 14:43 UTC, yostashiro requested changes

2023-01-05 14:43 UTC, yostashiro commented on purchase_report_shipping_address/reports/purchase_order_templates.xml
> +        </xpath>
```suggestion
```
I think this div (i.e. o.dest_address_id is true) is for dropship case and therefore should be intact.  Let me know if I've misunderstood something.

2023-01-05 14:43 UTC, yostashiro commented on purchase_report_shipping_address/reports/purchase_quotation_templates.xml
> +        </xpath>
```suggestion
```
Same as above.

2023-01-07 13:42 UTC, yostashiro approved these changes
Tested on runboat. 👍 

@AungKoKoLin1997 Please squash your commits.

2023-01-19 09:42 UTC, kakurai8 approved these changes
It works as expected. LGTM

2023-02-09 03:41 UTC, rinaldifirdaus approved these changes
Functional test: Working as expected

2023-04-25 09:59 UTC, HviorForgeFlow commented
/ocabot merge nobump

2023-04-25 10:10 UTC, merged